### ISSUE TITLE
请问XE-99S连接UART后一直处于跑码状态，无法输入命令有解吗

### ISSUE THREAD

**Issue by tjcfnerd** [YuukiJapanTech/CA8271x#1]
![image](https://github.com/YuukiJapanTech/CA8271x/assets/10485497/0594c2b5-335b-451e-9c97-dd8f91c816c5)
用的ch341a编程器连接到pc上
此设备由于之前设置了无效的mac地址导致设备无法自行设置ip地址

**Comment by YuukiJapanTech** [comment]
@tjcfnerd 
Is the fiber unconnected?
uart should accept input even if logs are continuously output. Are uart rx wires disconnected?

The logs indicate that dtb or mfginfo may be corrupted.
To repair this, you will need to transfer the dump via tftp or uboot and overwrite it.

**Comment by tjcfnerd** [comment]
@YuukiJapanTech 
已解决，需要将ch341a的GND也接上即可正常输入，另外我手上这根XE-99S的UART的root账户有密码，默认是admin，修改mac1后可正常开机

**Comment by YuukiJapanTech** [comment]
@tjcfnerd 
ok. Finally, can you provide a dump of the mtd0 ~ mtd10?
The XE-99S I have did not ask for a password. I assume it is a different firmware.

Host
`nc -l 10000 > mtd0.bin`

XE-99S
`cat /dev/mtd0 | nc 192.168.0.XXX 10000`

**Comment by tjcfnerd** [comment]
@YuukiJapanTech 
我手上的XE-99S系统分区信息如下
```
root@XE-99S:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00400000 00020000 "ssb"
mtd1: 00100000 00020000 "uboot-env"
mtd2: 00100000 00020000 "dtb1"
mtd3: 00600000 00020000 "kernel1"
mtd4: 02800000 00020000 "rootfs1"
mtd5: 00100000 00020000 "dtb0"
mtd6: 00600000 00020000 "kernel0"
mtd7: 02800000 00020000 "rootfs0"
mtd8: 01400000 00020000 "userdata"
mtd9: 00100000 00020000 "mfginfo1"
mtd10: 00100000 00020000 "mfginfo2"
mtd11: 00ba3000 0001f000 "squashfs_ubi"
mtd12: 01078000 0001f000 "userdata"
```

但是mtd12备份不出来，提示如下：
```
root@XE-99S:~# dd if=/dev/mtd12 of=/tmp/mtd12.bin
dd: can't open '/dev/mtd12': Device or resource busy
```

mtd0～mtd11及配置手册已上传到夸克网盘，分享链接为：https://pan.quark.cn/s/144596b9fc93
有效期7天

**Comment by YuukiJapanTech** [comment]
@tjcfnerd Thanks, the manual is verry interesting.

The firmware is the same as the Stick I have (CTC20220901/0xc41d, BuildDate 22/04/06 is little old)
and there was no password set.
(write and tried it, it was able to make UART connections and SSH without a password)

If there are no problems, I mark it as resolved🙂

**Comment by YuukiJapanTech** [comment]
Ahh, it was set in overlay, It was indeed set in root/admin, thanks!
